#!/bin/sh -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src

# set admin password (will be hashed) and secret
CONF=/etc/couchdb/local.ini
sed -i "s|^;admin =.*|$ADMIN_NAME = $ADMIN_PASS|" $CONF
cat >>$CONF<<EOF

[couch_httpd_auth]
secret = $(mcookie)
EOF

# configure nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/couchdb /etc/nginx/sites-enabled/couchdb

# install couchapp
pip install $SRC/couchapp/argparse-*
pip install $SRC/couchapp/pathtools-*
pip install $SRC/couchapp/argh-*
pip install $SRC/couchapp/PyYAML-*
pip install $SRC/couchapp/WebOb-*
pip install $SRC/couchapp/nose-*
pip install $SRC/couchapp/socketpool-*
pip install $SRC/couchapp/http-parser-*
pip install $SRC/couchapp/watchdog-*
pip install $SRC/couchapp/restkit-*
pip install $SRC/couchapp/Couchapp-*
rm -rf $SRC/couchapp

